name: Create Workflow

on:
  schedule:
    - cron: '* * * * *'  # run every hour

jobs:
  create-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new repositories
        id: list-repos
        uses: octokit/request-action@v2.x
        with:
          route: GET /user/repos
          headers: |
            Authorization: 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
          query: |
            sort: created
            direction: desc
      - name: Create workflow in new repositories
        uses: peter-evans/create-pull-request@v3.9.1
        with:
          commit-message: "Add workflow file"
          branch: "add-workflow-file"
          title: "Add workflow file"
          body: |
            This pull request adds a workflow file to the repository.
          path: ".github/workflows/main.yml"
          branch-suffix: timestamp
          token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.list-repos.outputs.data[0].created_at > github.event.created_at }}
