name: 
  Create Workflow

on:
  schedule:
    - cron: '* * * * *' # Run every hour

jobs:
  create-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new repositories
        id: list-repos
        uses: octokit/request-action@v2.x
        with:
          route: GET /user/repos
          headers: |
            Authorization: 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
          query: |
            sort: created
            direction: desc
      - name: Create workflow in new repositories
        run: |
          for repo in "${{ steps.list-repos.outputs.data[*].full_name }}"; do
            workflow_file_path="${repo}/.github/workflows/my-workflow.yml"
            if [[ ! -f $workflow_file_path ]]; then
              mkdir -p "${repo}/.github/workflows"
              touch "${workflow_file_path}"
              echo "name: My Workflow\n\non:\n  push:\n    branches:\n      - master\n\njobs:\n  build:\n    name: Build\n    runs-on: ubuntu-latest\n    steps:\n      - uses: anas203044/global/globalaction@main\n        with:\n          sonar-token: \${{ secrets.SONAR_TOKEN }}\n          sonar-host-url: \${{ secrets.SONAR_HOST_URL }}" >> "${workflow_file_path}"
              git -C "${repo}" add "${workflow_file_path}"
              git -C "${repo}" commit -m "Add workflow file"
              git -C "${repo}" push origin master
            fi
          done
