name: New Repositories
on:
  push:
    branches:
      - main
jobs:
  list_repositories:
    name: List New Repositories
    runs-on: ubuntu-latest
    steps:
      - name: Get Repositories
        id: repos
        run: |
          response=$(curl -s -H "Authorization: token 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" "https://api.github.com/user/repo")
          echo "::set-output name=response::$response"
      - name: Check for New Repositories
        run: |
          previous_repos=$(cat previous_repos.txt)
          current_repos=$(echo "${{ steps.repos.outputs.response }}" | jq -r '.[].name')
          new_repos=$(echo "$current_repos" | grep -Fxv "$previous_repos")
          if [ -n "$new_repos" ]; then
            echo "New repositories added: $new_repos"
          else
            echo "No new repositories"
          fi
          echo "$current_repos" > previous_repos.txt
        env:
          GITHUB_TOKEN: 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
